# Generated by Django 5.2.4 on 2025-07-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotedatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст цитаты')),
                ('source', models.CharField(verbose_name='Источник')),
                ('weight', models.PositiveIntegerField(verbose_name='Вес')),
                ('likes', models.PositiveIntegerField(verbose_name='Лайки')),
                ('dislikes', models.PositiveIntegerField(verbose_name='Дизлайки')),
                ('views', models.PositiveIntegerField(verbose_name='Просмотры')),
            ],
        ),
    ]
