# Generated by Django 5.2.4 on 2025-07-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotedatabase',
            options={'verbose_name': 'цитаты', 'verbose_name_plural': 'цитаты'},
        ),
        migrations.AlterField(
            model_name='quotedatabase',
            name='dislikes',
            field=models.PositiveIntegerField(default=0, verbose_name='Дизлайки'),
        ),
        migrations.AlterField(
            model_name='quotedatabase',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='quotedatabase',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
