# Generated by Django 5.2.4 on 2025-07-20 06:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_quotedatabase_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotedatabase',
            name='text',
            field=models.TextField(max_length=500, unique=True, verbose_name='Текст цитаты'),
        ),
        migrations.AlterField(
            model_name='quotedatabase',
            name='weight',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Вес'),
        ),
    ]
