# Generated by Django 5.2.4 on 2025-07-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_quotedatabase_text_alter_quotedatabase_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotedatabase',
            name='source',
            field=models.CharField(max_length=255, verbose_name='Источник'),
        ),
    ]
