# Generated by Django 5.2.4 on 2025-07-20 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_quotedatabase_source'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quotedatabase',
            new_name='Quotes',
        ),
    ]
